public with sharing class HelloController {
    
public static String hello(){
    System.debug('CODIGO COPIADO');
    System.debug('CODIGO COPIADO');
    System.debug('CODIGO COPIADO');
    System.debug('CODIGO COPIADO');
    return 'Hello Jogador';
}

public static String helloParametrizado(String strParam){
    System.debug('CODIGO COPIADO');
    System.debug('CODIGO COPIADO');
    System.debug('CODIGO COPIADO');
    System.debug('CODIGO COPIADO');
    return 'Valor enviado: '+strParam;
}

}
